#!/usr/bin/env node
// Generates site/tokens.css from DESIGN.md.
//
// Colors, spacing, and rounded values come straight from the
// `design.md export --format dtcg` CLI output (the CLI's own understanding
// of the file). Typography is read from the DESIGN.md front matter directly
// because the installed CLI's dtcg exporter currently drops `lineHeight`
// from typography tokens (verified against @google/design.md@0.3.0) — this
// keeps the generated CSS faithful to what DESIGN.md actually specifies.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import YAML from "yaml";

const rootDir = path.resolve(fileURLToPath(import.meta.url), "../..");
const designMdPath = path.join(rootDir, "DESIGN.md");
const outPath = path.join(rootDir, "site", "tokens.css");

const dtcgJson = execFileSync(
  "npx",
  ["design.md", "export", "--format", "dtcg", designMdPath],
  { cwd: rootDir, encoding: "utf8" }
);
const dtcg = JSON.parse(dtcgJson);

const raw = readFileSync(designMdPath, "utf8");
const frontMatterMatch = raw.match(/^---\n([\s\S]*?)\n---/);
if (!frontMatterMatch) throw new Error("DESIGN.md has no front matter");
const frontMatter = YAML.parse(frontMatterMatch[1]);

const dim = (d) => (typeof d === "number" ? `${d}px` : `${d.value}${d.unit}`);
const lines = [];

lines.push(
  "/* AUTO-GENERATED by scripts/build-tokens.mjs from DESIGN.md. Do not edit by hand —",
  "   edit DESIGN.md and run `npm run build:tokens` instead. */",
  ":root {"
);

lines.push("  /* colors */");
for (const [name, token] of Object.entries(dtcg.color ?? {})) {
  if (name.startsWith("$")) continue;
  lines.push(`  --color-${name}: ${token.$value.hex};`);
}

lines.push("", "  /* spacing */");
for (const [name, token] of Object.entries(dtcg.spacing ?? {})) {
  if (name.startsWith("$")) continue;
  lines.push(`  --space-${name}: ${dim(token.$value)};`);
}

lines.push("", "  /* shape */");
for (const [name, token] of Object.entries(dtcg.rounded ?? {})) {
  if (name.startsWith("$")) continue;
  lines.push(`  --radius-${name}: ${dim(token.$value)};`);
}

lines.push("", "  /* typography (read from DESIGN.md front matter, see header note) */");
for (const [name, t] of Object.entries(frontMatter.typography ?? {})) {
  lines.push(`  --type-${name}-family: '${t.fontFamily}';`);
  if (t.fontSize) lines.push(`  --type-${name}-size: ${t.fontSize};`);
  if (t.fontWeight) lines.push(`  --type-${name}-weight: ${t.fontWeight};`);
  if (t.lineHeight) lines.push(`  --type-${name}-leading: ${t.lineHeight};`);
  if (t.letterSpacing) lines.push(`  --type-${name}-tracking: ${t.letterSpacing};`);
}

lines.push("}", "");

for (const [name, t] of Object.entries(frontMatter.typography ?? {})) {
  lines.push(
    `.text-${name} {`,
    `  font-family: var(--type-${name}-family);`,
    t.fontSize && `  font-size: var(--type-${name}-size);`,
    t.fontWeight && `  font-weight: var(--type-${name}-weight);`,
    t.lineHeight && `  line-height: var(--type-${name}-leading);`,
    t.letterSpacing && `  letter-spacing: var(--type-${name}-tracking);`,
    "}"
  );
}

const css = lines.filter(Boolean).join("\n") + "\n";
writeFileSync(outPath, css);
console.log(`Wrote ${path.relative(rootDir, outPath)} from DESIGN.md`);
